_target_: models.ViT
im_size: ${dataset.im_size}
num_classes: ${dataset.num_classes}
in_channels: ${dataset.im_channels}
patch_size: [4, 4]
feature_dim: 32
num_layers: 4
dim_ff: 256
nhead: 8
dropout: 0.1
norm_first: True
activation: relu