# Full list of kwargs:
# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html
_target_: sklearn.neural_network.MLPClassifier
hidden_layer_sizes:
  - 100
activation: relu
solver: adam
batch_size: auto
learning_rate_init: 0.001
max_iter: 5000
early_stopping: True
random_state: ${seed}